### ISSUE TITLE
Switch primary branch to main

### ISSUE THREAD

**Issue by btmills** [eslint/tsc-meetings#309]
We've already made this migration in most other repositories. There are only two non-Markdown files that contain the string "master", and one is an outdated link in a comment:

1. https://github.com/eslint/tsc-meetings/blob/d5bfb229cbf21cea1f97864c9a4703d390d31131/.github/workflows/ci.yml#L5-L8
1. https://github.com/eslint/tsc-meetings/blob/361909c7b027ddf7b47a6f9c99ebae09e3dec428/scripts/generate-transcript.js#L10

The [`generate-transcript`](https://github.com/eslint/tsc-meetings/blob/master/.github/workflows/generate-transcript.yml) CI workflow automatically creates the pull request against the default base branch.

- [x] Update the CI workflow to reference `main` in addition to `master`. #310
- [x] Use GitHub's branch rename feature to make `main` the primary branch.
- [ ] Update the CI workflow to only reference `main`. #312
- [x] At any point, update the `generate-transcript.js` comment to an up-to-date permalink. #311
